{% set python_min = "3.9.0" %}
{% set name = "robocorp-tasks" %}
{% set version = "4.0.0" %}
{% set python_min = "3.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/robocorp_tasks-{{ version }}.tar.gz
  sha256: dbb7567539f04e60e91e2bf0a0a28ad4c545341dd83c8437b97bda0624eaad6f

build:
  noarch: python
  script:
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  number: 0
requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - robocorp-log >=2.4,<4
    - psutil <6.0,>=5.0
    - docstring_parser_fork <0.0.6,>=0.0.5
    - packaging <25.0,>=24.0

test:
  imports:
    - robocorp.tasks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/robocorp/robo/
  summary: The automation framework for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - zaigner
