{% set name = "robocorp-tasks" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robocorp_tasks-{{ version }}.tar.gz
  sha256: db99e370d183b4ab7a4ecdc835e40072828dd6ea24d0df66a3ce7ea7ad9259b5

build:
  noarch: python
  script:
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  number: 0
requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - robocorp-log >=2.4,<3
    - psutil >=5.9.0,<6.0.0
    - docstring_parser_fork >=0.0.5,<0.0.6

test:
  imports:
    - robocorp.tasks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robocorp/robo/
  summary: The automation framework for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - zaigner
