{% set name = "robocorp-tasks" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robocorp_tasks-{{ version }}.tar.gz
  sha256: 17ec52f93714482ab45c1e615fa1f591847d85b600b86978f03201414dc86b9c

build:
  noarch: python
  script:
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  number: 0
requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - robocorp-log >=2.4,<3

test:
  imports:
    - robocorp.tasks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robocorp/robo/
  summary: The automation framework for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - zaigner
